#!/bin/bash
# These things are run when an Openbox X Session is started.
#

# GNOME config tools
#
if [ -x /usr/lib/openbox/gnome-settings-daemon ] >/dev/null; then
  /usr/lib/openbox/gnome-settings-daemon &
elif which gnome-settings-daemon >/dev/null 2>&1; then
  gnome-settings-daemon &
fi

loop-command 10m 0 grive -p /home/flyin1501/ドキュメント/ &
ssh-agent &
ssh-add </dev/null
numlockx &

randomwallpaper -t 5m -w feh &

compton &
xcape -e 'Alt_R=Escape;Super_L=Alt_L|F1' -t 250 &
dunst &

bar &
latte-dock &

xmodmap ~/.Xmodmap.d/capslock-to-altgr.xmodmap
xmodmap ~/.Xmodmap

xsetwacom --set "Wacom Intuos PT S 2 Pen stylus" Area 0 0 15200 8550

# vim: filetype=sh
