#!/bin/bash
# These things are run when an Openbox X Session is started.
#
__run_if_present () {
    command -v "$1" >/dev/null 2>/dev/null && "$@"
}

# GNOME config tools
if [ -x /usr/lib/openbox/gnome-settings-daemon ] >/dev/null; then
  /usr/lib/openbox/gnome-settings-daemon &
elif which gnome-settings-daemon >/dev/null 2>&1; then
  gnome-settings-daemon &
fi

# Polkit agent
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/polkit-kde-authentication-agent-1 &

loop-command 10m 0 grive -p /home/flyin1501/ドキュメント/ &
ssh-agent &
ssh-add </dev/null
numlockx &

randomwallpaper -t 5m -w plasma -o &

xcompmgr &
xcape -e 'Alt_R=Escape;Super_L=Alt_L|F1' -t 250 &
dunst &

# Uh-huh.
plasmashell &
bar &
latte-dock &

xmodmap ~/.Xmodmap.d/capslock-to-altgr.xmodmap
xmodmap ~/.Xmodmap

xsetwacom --set "Wacom Intuos PT S 2 Pen stylus" Area 0 0 15200 8550

__run_if_present aw-qt &

# vim: filetype=sh
